scitokens/scitokens-cpp

src/scitokens_internal.h
If an audience is set for the validator, force a test of the
aud parameter, even if it's not in the token
=> Force aud test in the validator

src/scitokens.cpp, src/scitokens.h
Using `const char**` does not allow implicit conversion from `char**`.  It has to be protected at both level of de-reference:  `char const* const*`
=> Use double layer of const for deserialize

CMakeLists.txt, src/scitokens.cpp, src/scitokens_internal.cpp, src/scitokens_internal.h
Fixes:
- Warnings due to an unused static function.
- Passing polymorphic exceptions by value.
- OpenSSL 1.1 API changes.
=> Fix build failures

src/scitokens_internal.cpp
This commit adds some bugfixes required for supporting IAM; there's nothing specific to that particular issuer, but rather some technical issues with `scitokens-cpp`:
1.  Incorrect handling of the padding in the `base64` pieces of the public keys.
2.  Do not require the (optional) `alg` claim in the public key; instead, try to bootstrap this from the (required) `kty` if `alg` isn't available.
=> Add support for IAM

CMakeLists.txt, src/create.cpp, src/scitokens.cpp, src/scitokens.h, src/scitokens_internal.cpp, src/scitokens_internal.h, src/verify.cpp
This adds support for the WLCG profile, in addition to a number of tools to help in the testing of tokens.
One can now do the following:
```
export TOKEN=$(./scitokens-create --cred test.pem --key test.pem --keyid 1 --issuer https://demo.scitokens.org --claim 'scp=read:/' --claim foo=bar --profile scitokens2)
./scitokens-verify  --keyid 1 --issuer https://demo.scitokens.org --cred test.pem $TOKEN
```
(Even without WiFi!)
=> Add support for the WLCG profile

.github/workflows/ccpp.yml, CMakeLists.txt, src/scitokens.cpp, src/scitokens.h, src/scitokens_internal.cpp, src/scitokens_internal.h, test/CMakeLists.txt
Hm - it seems that gtest referred to some APIs that didn't exist and some test cases didn't pass.  Looks like the original gtest branch was missing a few commits (bad rebase perhaps)?
Regardless, with this, gtest now works again!
@djw8605 - can you ensure that gtest is being invoked by the GH actions workflows?
=> Fix gtest APIs and test cases

src/scitokens.cpp, src/scitokens.h, src/scitokens_internal.h, test/main.cpp
This adds a simple API for querying for a list of strings set as values in a claim.
This should be useful for things in the future such as getting a list of groups from the token's claims.
(NOTE: This is built on the `fix_gtest` branch in #23 -- merge that first)
=> API for querying for string lists

src/scitokens_internal.h
GCC 11 just turned up in Fedora Rawhide, causing the following error:
error: loop variable 'verification_pair' creates a copy from type 'const std::pair<bool (*)(const jwt::claim&, void*), void*>' [-Werror=range-loop-construct]
=> Fix compilation error with gcc 11

src/scitokens.cpp, src/scitokens_cache.cpp, src/scitokens_internal.cpp, src/scitokens_internal.h
This PR fixes #33 and replaces #16 by fixing some compiler errors and updating to use jwt-cpp 0.4.0 (the latest stable release).
=> Update to jwt-cpp-0.4.0

CMakeLists.txt, test/CMakeLists.txt
This PR modifies the `CMakeLists.txt` to use [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) to define the default install destinations. This is pretty standard and is expected to be used by [conda build](https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/6290f55b73a887086b0efe0cdb32553646696a8a/recipe/activate-gcc.sh#L144), [`debhelper`](https://github.com/Debian/debhelper/blob/5d1bb29841043d8e47ebbdd043e6cd086cad508e/lib/Debian/Debhelper/Buildsystem/cmake.pm#L14-L21), and [`rpmbuild`](https://src.fedoraproject.org/rpms/cmake/blob/f34/f/macros.cmake#_29).
=> Use GNUInstallDirs to define default cmake install destinations

CMakeLists.txt, test/CMakeLists.txt
This PR adds a new CMake option `EXTERNAL_GTEST` (default `OFF`) which allows disabling the build of the vendored `gtest` for the test suite.
~~I also added `-DBUILD_UNITTESTS:BOOL=TRUE -DEXTERNAL_GTEST:BOOL=TRUE` and a `%check` section to the rpm build to run the tests there.~~ EDIT: this was dropped because EPEL7's `gtest` is too old, and adding a bunch of `%if` macros in the spec file seemed like a lot of work...
Fixed #46.
=> Allow disabling build of vendored gtest with new cmake option EXTERNAL_GTEST

src/scitokens_internal.cpp
Since std::vector<>.reserve() does not allocate,
accessing elements may lead to undefined behaviour
(and triggers asserts with build fortification on CentOS 8).
Use resize() as-needed instead to allocate the necessary space.
This is basically a variant of #39. The associated trace was:
```
#0  0x00007f3ff757f7ff in raise () from /lib64/libc.so.6
#1  0x00007f3ff7569c35 in abort () from /lib64/libc.so.6
#2  0x00007f3ff048b2d8 in std::__replacement_assert (__file=__file@entry=0x7f3ff04a8bc8 "/usr/include/c++/8/bits/stl_vector.h", __line=__line@entry=932, 
__function=__function@entry=0x7f3ff04a9440 <std::vector<char, std::allocator<char> >::operator[](unsigned long)::__PRETTY_FUNCTION__> "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, …
```
=> scitokens_internal: Fix undefined behaviour in CURL write functions.

src/scitokens_internal.cpp
=> Fixup WLCG compat for HTCondor READ

README.md, cmake/FindUUID.cmake, debian/README.obs, debian/obsupdate.sh, debian/scitokens-cpp.dsc, rpm/scitokens-cpp.spec
This adds support for building for Debian in cvmfs-contrib's Opensuse Build System.  It updates to version 0.6.3 at the same time because that affects the Debian package.
This doesn't build on Debian 11, Ubuntu 20.10, or Ubuntu 21.04 because of a compilation problem in jwt-cpp.  I think that might be fixed by updating that submodule to the latest version, but as it turns out it's not so important because OBS doesn't need to build scitokens-cpp in Debian 11 or Ubuntu 21.04 because it's already natively available there.  It still might be wanted for Ubuntu 20.10.
So really, this is only for support on Debian versions older than 11 and Ubuntu versions older than 21.04.
=> Add support for building debian in cvmfs-contrib OBS

README.md, rpm/scitokens-cpp.spec
This gives a variable name to substitute for the all the places the version number is needed.
=> Simplify build instructions

rpm/scitokens-cpp.spec
This makes the %ldconfig_scriptlets macro work on el7.  Discussed in #62.
=> Add requiring epel-rpm-macros on el7

src/scitokens_internal.cpp, src/scitokens_internal.h
When `kid` is not set and only a single key is published, fall back to using this single key.
This expands upon #7 (and pulls in the commit part of that PR) and adds a modification to `find_key_id` to deal with an empty `kid`. 
Adresses parts of the issues observed in #53 .
=> Allow empty Key-ID / kid if only a single key is published

src/create.cpp, src/scitokens.h, src/scitokens_internal.h, src/verify.cpp, test/main.cpp
This adds support for the at-jwt type (RFC9068),
indicated and detectable from the `typ` header claim
as outlined in RFC8725 Section 3.11.
Used by Unity IAM which is used e.g. by the Helmholtz AAI.
This addresses #53. After applying this PR and #55, Unity IAM tokens are accepted in the `COMPAT` profile and the new `AT_JWT` profile. The `COMPAT` profile detects the `typ` header claim and switches to that accordingly.
=> Add support for at+jwt profile.

src/scitokens.cpp, src/scitokens_cache.cpp, src/scitokens_internal.cpp
Several minor fixes for complaints found by static analysis.
=> Fix minor complaints found by static analysis

CMakeLists.txt
If unit tests are enabled only the header file is installed.
=> Enabling unit tests should not disable install of libraries and binaries

CMakeLists.txt, test/CMakeLists.txt
Add cmake option to turn on/off -Werror (warnings are errors)
-Werror is unconditonally on before this change, which is now considered
poor practice -- it means that the library may refuse to build on
arbirtray compilers or systems that add new warnings.  In particular,
systems with openssl 3 generate an ocean of deprecation warnings.
This change adds a cmake option to turn -Werror back on with
cmake -DSCITOKENS_WARNINGS_ARE_ERRORS:bool=true ...
=> Warnings as errors option

CMakeLists.txt, test/CMakeLists.txt
This entails changing most global variables to target attributes
and being careful about PUBLIC vs PRIVATE target attributes.
For those global variables we must have, like the options,
give them a SCITOKENS prefix as an ersatz namespace.
Also, it means using built-in cmake mechanisms to set things like the minimum
C++ standard required, debugging and optimization flags in a portable manner.
Note that with these changes, scitokens-cpp is now cmake fetchable.
That is, a client can chose to use this library in their own cmake
by just doing this:
include(FetchContent)
FetchContent_Declare(SciTokens
GIT_REPOSITORY https://github.com/scitokens/scitokens-cpp
GIT_TAG        master)
FetchContent_MakeAvailable(SciTokens)
add_executable(test test.cpp)
target_link_libraries(test SciTokens)
And all …
=> Convert CMakeLists.txt to "modern" cmake style

src/scitokens_cache.cpp
(attn: @brianhlin @djw8605, i don't have permissions to assign a reviewer for this)
I'm seeing condor_schedd accumulating open fds pointing to `/var/lib/condor/.cache/scitokens/scitokens_cpp.sqllite` (thousands), without ever getting closed.
I looked around the sources here and _every_ other `return` in a function that opens this db is preceeded by a `sqlite3_close(db);` .  Presumably this one here is the source of the leak and just got missed.
=> fix apparent fd-leak of sqlite handle

.github/workflows/ccpp.yml, test/CMakeLists.txt
This adapts the unit tests (in GitHub actions) to use the now prefixed CMake flags, changed as part of #84 .
Thanks for the very welcome change :+1: .
=> gh-action: Adapt unittests to renamed CMake flags, fix using external gtest.

test/CMakeLists.txt
Follow-up on my comment on #89.
=> CMake: don't add bundled gtest include dir when using external gtest

src/scitokens.cpp, src/scitokens.h, src/scitokens_internal.h, test/main.cpp
For XRootD, we decided that the "time" the session token should be evaluated should be when the session starts and not when the operation is attempted; this allows session authorizations to live longer than the token (this matches how X.509 works -- expiration time is only checked at start).
Hence, at the SciTokens library level we must allow the user to explicitly set the clock backward for token evaluation.
Implementation is rather straightforward - unit test is included.
=> Allow the library user to explicitly set the "current" time.

src/scitokens_internal.cpp, src/scitokens_internal.h
While the public key download can fail and have the library fall back on the cached copy, this fallback can take such a long time that the application code (such as the HTCondor-CE) invoking the library times out its current operation and still failing.
So, without this, the fallback succeeds but everything else fails due to timeouts.
For now, we have arbitrarily set the timeout to 30s for the case where the pubkey has expired and 4s for the update check.
=> Shorten timeout for public key download

src/scitokens_internal.cpp, src/scitokens_internal.h
While the public key download can fail and have the library fall back on the cached copy, this fallback can take such a long time that the application code (such as the HTCondor-CE) invoking the library times out its current operation and still failing.
So, without this, the fallback succeeds but everything else fails due to timeouts.
For now, we have arbitrarily set the timeout to 30s for the case where the pubkey has expired and 4s for the update check.
=> Shorten timeout for public key download (backport)

src/scitokens_cache.cpp, src/scitokens_internal.cpp, src/scitokens_internal.h
Without this, a persistent failure in the key retrieval will not be remembered, meaning rapid-fire retries from the client will result in a similar number of key retrieval attempts.
This causes the next_update to be set forward by 5 minutes after each failure.
=> Avoid retrying for 5 minutes after failed key retrieval (backport)

.clang-format, .github/workflows/linter.yml
This commit adds a linter action that can automatically lint code in the repo. It's currently configured to analyze and automatically lint code whenever a PR is merged with master. The goal is to establish a cleaner and more structured code base. After the initial lint, the linter should only touch new/modified files.
=> Add a Linter action to the GitHub workflow

configs/export-symbols, src/scitokens.cpp, src/scitokens.h, src/scitokens_internal.cpp, src/scitokens_internal.h, test/main.cpp
Prior to this feature, the keycache was hard-coded to update every 10m and expire every 4d. This addition allows administrators to explicitly set these parameters to optimize behavior of the keycache in their systems.
=> Add configuration API to set keycache update/expiration intervals

src/scitokens_internal.h, test/main.cpp
After updating the vendored jwt-cpp version in:
a8c597775f44ad2fa0f7bde8d186aca9466757ab
the exception type if a claim is not found has changed, breaking the "no kid claim" use case.
Adapt the code to catch the new exception type.
This essentially broke:
https://github.com/scitokens/scitokens-cpp/pull/55
@djw8605 Can you think of a good test we could add to ensure this issue does not reappear?
=> scitokens_internal: catch matching exception type after jwt-cpp update

src/scitokens_internal.cpp, src/scitokens_internal.h, test/main.cpp
* Fix some compiler warnings
~~~
.../src/scitokens_internal.h:673:25: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
673 |         return std::move(result);
|                ~~~~~~~~~^~~~~~~~
.../src/scitokens_internal.h:673:25: note: remove 'std::move' call
.../src/scitokens_internal.cpp:633:25: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
633 |         return std::move(status);
|                ~~~~~~~~~^~~~~~~~
.../src/scitokens_internal.cpp:633:25: note: remove 'std::move' call
.../src/scitokens_internal.cpp:747:13: warning: unused variable 'next_update' [-Wunused-variable]
747 |     int64_t next_update, expires;
|             ^~~~~~~~~~~
.../src/scitokens_internal.cpp:747:26: warning: …
=> Test failures and compiler warnings

src/scitokens_internal.cpp, src/scitokens_internal.h
Limit key refresh to a single simultaneous request to avoid overloading issuers.
=> Add mutex around key refresh with get_public_keys_from_web()

CMakeLists.txt
Unity builds don't work in scitokens-cpp, but they wouldn't speed up builds much anyway, as there aren't a huge number of .cpp files per library. So, don't bother to fix the multiple inclusions problems that unity builds create, just disable the feature here.
Turning this off does allow scitokens-cpp to be built in a larger project that does turn on unity builds globally.
=> Disable CMake unity builds

CMakeLists.txt
This PR fixes the `target_include_directories` entry for discovering libcurl headers which is currently benignly broken.
=> Fix include_directories for libcurl

test/main.cpp
Needed for memory-leak clean CI runs.
=> Fix memory leaks in the unit tests

.github/workflows/ccpp.yml, CMakeLists.txt
=> Turn off building unit tests by default.

src/scitokens_internal.cpp
=> Set CURLOPT_NOSIGNAL option in SimpleCurlGet to prevent signal interruptions

src/verify.cpp
=> Send usage warning to stdout instead of stderr
